version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  terraform_init_and_validate:
    docker:
      - image: hashicorp/terraform:1.1.0  # Use an image with Terraform pre-installed
    environment:
      ARM_CLIENT_ID: ${ARM_CLIENT_ID}
      ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
      ARM_TENANT_ID: ${ARM_TENANT_ID}
      ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd prod
            terraform init
      - run:
          name: Validate Terraform Configuration
          command: |
            cd prod
            terraform validate

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_init_and_validate:
          filters:
            branches:
              only: prod
