version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: projectx  # Updated context to "projectx"
          path: "prod"  # This is illustrative; "path" parameter is not used by the Terraform orb
      - terraform/plan:
          checkout: true
          context: projectx  # Updated context to "projectx"
          persist-workspace: true
          requires:
            - terraform/validate
          path: "prod"  # This is illustrative; adjust your commands as needed if your Terraform files are in a subdirectory
      - terraform/apply:
          attach-workspace: true
          context: projectx  # Updated context to "projectx"
          filters:
            branches:
              only: prod  # Ensure this matches your intended deployment branch
          requires:
            - terraform/plan
          path: "prod"  # This is illustrative; adjust according to your directory structure

