version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  terraform_workflow:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      TF_ROOT: ~/project/prod
    steps:
      - checkout
      - run: 
          name: "Set Terraform Working Directory"
          command: |
            echo 'export TF_WORKING_DIR=$TF_ROOT' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Terraform Init
          command: |
            cd $TF_WORKING_DIR
            terraform init
      - run:
          name: Terraform Format
          command: |
            cd $TF_WORKING_DIR
            terraform fmt -check
      - run:
          name: Terraform Validate
          command: |
            cd $TF_WORKING_DIR
            terraform validate
      - run:
          name: Terraform Plan
          command: |
            cd $TF_WORKING_DIR
            terraform plan
      - run:
          name: Terraform Apply
          command: |
            cd $TF_WORKING_DIR
            terraform apply -auto-approve
          no_output_timeout: 30m

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_workflow:
          filters:
            branches:
              only: prod
