---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: 2.1
orbs: 
  terraform: circleci/terraform@3.1.0
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: projectx
      - terraform/plan:
          checkout: true
          context: projectx
          persist-workspace: true
          requires:
            - terraform/validate     
      - terraform/apply:
          attach-workspace: true
          context: projectx
          filters:
            branches:
              only: prod
          requires:
            - terraform/plan
