version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

jobs:
  terraform_validate:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - run: cd prod && terraform init
      - run: cd prod && terraform validate

  terraform_plan:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: cd prod && terraform init -reconfigure
      - run: cd prod && terraform plan -out=tfplan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - run: cd prod && terraform apply -auto-approve tfplan

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_validate:
          context: projectx
          filters:
            branches:
              only: prod
      - terraform_plan:
          context: projectx
          requires:
            - terraform_validate
          filters:
            branches:
              only: prod
      - terraform_apply:
          context: projectx
          requires:
            - terraform_plan
          filters:
            branches:
              only: prod
