version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: projectx  # Apply context at the job invocation within the workflow
          name: validate_terraform
          filters:
            branches:
              only: master  # Ensure this matches your intended deployment branch

      - terraform/plan:
          checkout: true
          context: projectx  # Apply context here as well
          name: plan_terraform
          requires:
            - validate_terraform
          filters:
            branches:
              only: master
          persist-workspace: true  # persist-workspace is used to pass data between jobs

      - terraform/apply:
          attach-workspace: true  # attach-workspace to use data persisted in the previous job
          context: projectx  # And apply context here
          name: apply_terraform
          requires:
            - plan_terraform
          filters:
            branches:
              only: master
