version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: Initialize Terraform
          command: |
            cd prod
            terraform init
      - persist_to_workspace:
          root: ~/project
          paths:
            - prod

  terraform_validate:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Validate Terraform Configuration
          command: |
            cd prod
            terraform validate

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_init
      - terraform_validate:
          requires:
            - terraform_init
          filters:
            branches:
              only: prod
