version: 2.1

jobs:
  terraform_workflow:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project  # Assuming the root of your checked-out repo is ~/project
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd prod  # Navigate into the 'prod' directory where your Terraform files are
            terraform init
      - run:
          name: Apply Terraform Configuration
          command: |
            cd prod  # Ensure we're still in the 'prod' directory
            terraform apply -auto-approve \
              -var "ARM_CLIENT_ID=${ARM_CLIENT_ID}" \
              -var "ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}" \
              -var "ARM_TENANT_ID=${ARM_TENANT_ID}" \
              -var "ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}"

workflows:
  version: 2
  deploy:
    jobs:
      - terraform_workflow:
          context: projectx  # Ensure this context contains your Azure credentials
