version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

jobs:
  terraform_validate:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: cd prod && terraform init
      - run: cd prod && terraform validate
    environment:
      ARM_CLIENT_ID: << parameters.arm_client_id >>
      ARM_CLIENT_SECRET: << parameters.arm_client_secret >>
      ARM_SUBSCRIPTION_ID: << parameters.arm_subscription_id >>

  terraform_plan:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Terraform Init
          command: cd prod && terraform init -reconfigure
      - run: cd prod && terraform plan -out=tfplan
    environment:
      ARM_CLIENT_ID: << parameters.arm_client_id >>
      ARM_CLIENT_SECRET: << parameters.arm_client_secret >>
      ARM_SUBSCRIPTION_ID: << parameters.arm_subscription_id >>

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: cd prod && terraform apply -auto-approve tfplan
    environment:
      ARM_CLIENT_ID: << parameters.arm_client_id >>
      ARM_CLIENT_SECRET: << parameters.arm_client_secret >>
      ARM_SUBSCRIPTION_ID: << parameters.arm_subscription_id >>

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_validate:
          context: projectx
          parameters:
            arm_client_id:
              description: "Azure client ID"
              type: env_var_name
            arm_client_secret:
              description: "Azure client secret"
              type: env_var_name
            arm_subscription_id:
              description: "Azure subscription ID"
              type: env_var_name
          filters:
            branches:
              only: prod
      - terraform_plan:
          context: projectx
          parameters:
            arm_client_id:
              description: "Azure client ID"
              type: env_var_name
            arm_client_secret:
              description: "Azure client secret"
              type: env_var_name
            arm_subscription_id:
              description: "Azure subscription ID"
              type: env_var_name
          requires:
            - terraform_validate
          filters:
            branches:
              only: prod
      - terraform_apply:
          context: projectx
          parameters:
            arm_client_id:
              description: "Azure client ID"
              type: env_var_name
            arm_client_secret:
              description: "Azure client secret"
              type: env_var_name
            arm_subscription_id:
              description: "Azure subscription ID"
              type: env_var_name
          requires:
            - terraform_plan
          filters:
            branches:
              only: prod
