version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

jobs:
  terraform_init_validate_plan_apply:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Change to Terraform Directory and Initialize
          command: |
            cd prod
            terraform init
      - run:
          name: Validate Terraform Configuration
          command: |
            cd prod
            terraform validate
      - run:
          name: Create Terraform Plan
          command: |
            cd prod
            terraform plan -out=tfplan
      - run:
          name: Apply Terraform Plan
          command: |
            cd prod
            terraform apply -auto-approve tfplan
    context: projectx

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_init_validate_plan_apply:
          filters:
            branches:
              only: master
