version: 2.1

jobs:
  terraform_plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Initialize and Plan Terraform Configuration
          command: |
            cd prod
            terraform init
            terraform plan -out=tfplan \
              -var "ARM_CLIENT_ID=${ARM_CLIENT_ID}" \
              -var "ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}" \
              -var "ARM_TENANT_ID=${ARM_TENANT_ID}" \
              -var "ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}"

  terraform_apply:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Apply Terraform Plan
          command: |
            cd prod
            terraform apply -auto-approve tfplan

workflows:
  version: 2
  deploy:
    jobs:
      - terraform_plan:
          context: projectx
      - hold_for_approval:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          context: projectx
          requires:
            - hold_for_approval
