version: 2.1

orbs:
  terraform: circleci/terraform@3.1

jobs:
  terraform_init_and_validate:
    docker:
      - image: hashicorp/terraform:1.1.0  # Specify the version of Terraform you need.
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Set up Azure Authentication Environment Variables
          command: |
            echo 'export ARM_CLIENT_ID=${ARM_CLIENT_ID}' >> $BASH_ENV
            echo 'export ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}' >> $BASH_ENV
            echo 'export ARM_TENANT_ID=${ARM_TENANT_ID}' >> $BASH_ENV
            echo 'export ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Initialize Terraform
          command: |
            cd prod
            terraform init
      - run:
          name: Validate Terraform Configuration
          command: |
            cd prod
            terraform validate

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform_init_and_validate:
          filters:
            branches:
              only: prod
