version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

jobs:
  setup_azure_credentials:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Export Azure Credentials
          command: |
            echo 'export ARM_CLIENT_ID=${ARM_CLIENT_ID}' >> $BASH_ENV
            echo 'export ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}' >> $BASH_ENV
            echo 'export ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}' >> $BASH_ENV
            echo 'export ARM_TENANT_ID=${ARM_TENANT_ID}' >> $BASH_ENV
    context: projectx

  terraform_init_validate_plan_apply:
    docker:
      - image: hashicorp/terraform:1.1.0
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Initialize Terraform
          command: |
            cd prod
            terraform init
      - run:
          name: Validate Terraform Configuration
          command: |
            cd prod
            terraform validate
      - run:
          name: Terraform Plan
          command: |
            cd prod
            terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: |
            cd prod
            terraform apply -auto-approve tfplan
    context: projectx

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - setup_azure_credentials
      - terraform_init_validate_plan_apply:
          requires:
            - setup_azure_credentials
          filters:
            branches:
              only: prod
